# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/Lenovo/Desktop/Frodo/prj/Frodo_top/Frodo_top.runs/synth_1/Top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param power.BramSDPPropagationFix 1
set_param power.enableUnconnectedCarry8PinPower 1
set_param power.enableCarry8RouteBelPower 1
set_param power.enableLutRouteBelPower 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config  -id {Common 17-69}  -string {{ERROR: [Common 17-69] Command failed: Synthesis failed - please see the console or run log file for details}}  -suppress 
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xczu7ev-ffvc1156-2-i

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Lenovo/Desktop/Frodo/prj/Frodo_top/Frodo_top.cache/wt [current_project]
set_property parent.project_path C:/Users/Lenovo/Desktop/Frodo/prj/Frodo_top/Frodo_top.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/Lenovo/Desktop/Frodo/prj/Frodo_top/Frodo_top.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib {
  C:/Users/Lenovo/Desktop/Frodo/rtl/Control/AGU.v
  C:/Users/Lenovo/Desktop/Frodo/rtl/Control/AGU_hash.v
  C:/Users/Lenovo/Desktop/Frodo/rtl/Control/Bus.v
  C:/Users/Lenovo/Desktop/Frodo/rtl/Control/Control.v
  C:/Users/Lenovo/Desktop/Frodo/rtl/Core.v
  C:/Users/Lenovo/Desktop/Frodo/rtl/Control/Datapre.v
  C:/Users/Lenovo/Desktop/Frodo/rtl/Decode.v
  C:/Users/Lenovo/Desktop/Frodo/rtl/Encode.v
  C:/Users/Lenovo/Desktop/Frodo/rtl/Macs/Macs.v
  C:/Users/Lenovo/Desktop/Frodo/rtl/Macs/PE_Simple.v
  C:/Users/Lenovo/Desktop/Frodo/rtl/Transpose.v
  C:/Users/Lenovo/Desktop/Frodo/rtl/Hash_v1.1/chiiota.v
  C:/Users/Lenovo/Desktop/Frodo/rtl/Hash_v1.1/hash_out_buffer.v
  C:/Users/Lenovo/Desktop/Frodo/rtl/Hash_v1.1/keccak.v
  C:/Users/Lenovo/Desktop/Frodo/rtl/Hash_v1.1/pre_theta.v
  C:/Users/Lenovo/Desktop/Frodo/rtl/sample.v
  C:/Users/Lenovo/Desktop/Frodo/rtl/Hash_v1.1/theta.v
  C:/Users/Lenovo/Desktop/Frodo/rtl/Control/ucontrol.v
  C:/Users/Lenovo/Desktop/Frodo/rtl/Top.v
}
read_ip -quiet C:/Users/Lenovo/Desktop/Frodo/prj/Frodo_top/Frodo_top.srcs/sources_1/ip/DRAM1/DRAM1.xci
set_property used_in_implementation false [get_files -all c:/Users/Lenovo/Desktop/Frodo/prj/Frodo_top/Frodo_top.gen/sources_1/ip/DRAM1/DRAM1_ooc.xdc]

read_ip -quiet C:/Users/Lenovo/Desktop/Frodo/prj/Frodo_top/Frodo_top.srcs/sources_1/ip/DRAM2/DRAM2.xci
set_property used_in_implementation false [get_files -all c:/Users/Lenovo/Desktop/Frodo/prj/Frodo_top/Frodo_top.gen/sources_1/ip/DRAM2/DRAM2_ooc.xdc]

read_ip -quiet C:/Users/Lenovo/Desktop/Frodo/prj/Frodo_top/Frodo_top.srcs/sources_1/ip/DRAM3/DRAM3.xci
set_property used_in_implementation false [get_files -all c:/Users/Lenovo/Desktop/Frodo/prj/Frodo_top/Frodo_top.gen/sources_1/ip/DRAM3/DRAM3_ooc.xdc]

read_ip -quiet C:/Users/Lenovo/Desktop/Frodo/prj/Frodo_top/Frodo_top.srcs/sources_1/ip/DRAM4/DRAM4.xci
set_property used_in_implementation false [get_files -all c:/Users/Lenovo/Desktop/Frodo/prj/Frodo_top/Frodo_top.gen/sources_1/ip/DRAM4/DRAM4_ooc.xdc]

read_ip -quiet C:/Users/Lenovo/Desktop/Frodo/prj/Frodo_top/Frodo_top.srcs/sources_1/ip/DRAM5/DRAM5.xci
set_property used_in_implementation false [get_files -all c:/Users/Lenovo/Desktop/Frodo/prj/Frodo_top/Frodo_top.gen/sources_1/ip/DRAM5/DRAM5_ooc.xdc]

read_ip -quiet C:/Users/Lenovo/Desktop/Frodo/prj/Frodo_top/Frodo_top.srcs/sources_1/ip/DRAM6/DRAM6.xci
set_property used_in_implementation false [get_files -all c:/Users/Lenovo/Desktop/Frodo/prj/Frodo_top/Frodo_top.gen/sources_1/ip/DRAM6/DRAM6_ooc.xdc]

read_ip -quiet C:/Users/Lenovo/Desktop/Frodo/prj/Frodo_top/Frodo_top.srcs/sources_1/ip/DRAM7/DRAM7.xci
set_property used_in_implementation false [get_files -all c:/Users/Lenovo/Desktop/Frodo/prj/Frodo_top/Frodo_top.gen/sources_1/ip/DRAM7/DRAM7_ooc.xdc]

read_ip -quiet C:/Users/Lenovo/Desktop/Frodo/prj/Frodo_top/Frodo_top.srcs/sources_1/ip/DRAM8/DRAM8.xci
set_property used_in_implementation false [get_files -all c:/Users/Lenovo/Desktop/Frodo/prj/Frodo_top/Frodo_top.gen/sources_1/ip/DRAM8/DRAM8_ooc.xdc]

read_ip -quiet C:/Users/Lenovo/Desktop/Frodo/prj/Frodo_top/Frodo_top.srcs/sources_1/ip/dual_ram/dual_ram.xci
set_property used_in_implementation false [get_files -all c:/Users/Lenovo/Desktop/Frodo/prj/Frodo_top/Frodo_top.gen/sources_1/ip/dual_ram/dual_ram_ooc.xdc]

read_ip -quiet C:/Users/Lenovo/Desktop/Frodo/prj/Frodo_top/Frodo_top.srcs/sources_1/ip/rom/rom.xci
set_property used_in_implementation false [get_files -all c:/Users/Lenovo/Desktop/Frodo/prj/Frodo_top/Frodo_top.gen/sources_1/ip/rom/rom_ooc.xdc]

read_ip -quiet C:/Users/Lenovo/Desktop/Frodo/prj/Frodo_top/Frodo_top.srcs/sources_1/ip/uinst_rom/uinst_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/Lenovo/Desktop/Frodo/prj/Frodo_top/Frodo_top.gen/sources_1/ip/uinst_rom/uinst_rom_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Lenovo/Desktop/Frodo/prj/Frodo_top/Frodo_top.srcs/constrs_1/new/clk.xdc
set_property used_in_implementation false [get_files C:/Users/Lenovo/Desktop/Frodo/prj/Frodo_top/Frodo_top.srcs/constrs_1/new/clk.xdc]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental C:/Users/Lenovo/Desktop/Frodo/prj/Frodo_top/Frodo_top.srcs/utils_1/imports/synth_1/Top.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top Top -part xczu7ev-ffvc1156-2-i
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file Top_utilization_synth.rpt -pb Top_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
