# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Lenovo/Desktop/Frodo/prj/Frodo_top/Frodo_top.srcs/sources_1/ip/DRAM4/DRAM4.xci
# IP: The module: 'DRAM4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Lenovo/Desktop/Frodo/prj/Frodo_top/Frodo_top.gen/sources_1/ip/DRAM4/DRAM4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DRAM4'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/Lenovo/Desktop/Frodo/prj/Frodo_top/Frodo_top.srcs/sources_1/ip/DRAM4/DRAM4.xci
# IP: The module: 'DRAM4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Lenovo/Desktop/Frodo/prj/Frodo_top/Frodo_top.gen/sources_1/ip/DRAM4/DRAM4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DRAM4'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
